setwd("E:/code/R")
fi<-read.csv("heart.csv")
print(fi)
install.packages("caret")
library("caret")
w=createDataPartition(y=fi$target,p=0.7,list=FALSE)
train=fi[w,]
test=fi[-w,]
print(train)
print(test)
fj<-read.csv("heart_failure_clinical_records_dataset.csv")
print(fj)

w=createDataPartition(y=fj$DEATH_EVENT,p=0.7,list=FALSE)
train=fj[w,]
test=fj[-w,]
print(train)
print(test)
print(nrow(fj))
print(ncol(fj))
print(nrow(train))
print(nrow(test))
