a<-read.csv("ai6oct.csv")
print(a)
b<-max(a$student_marks)
print(b)
b<-subset(a , student_marks==max(student_marks))
print(b)
c<-subset(a , student_dept=="cse")
print(c)
d<-subset(a , student_hobby=="cricket" & student_dept=="ece")
print(d)
e<-read.table("ai12oct1.txt", TRUE, sep="," ,quote = "\"")
print(e)
