uid<-c(1,2,3,4)
marks<-c(40,30,50,45)
op<-lm(marks ~ uid)
print(op)
print(summary(op))
x<-data.frame(uid=6)
y<- predict(op,x)
print(y)
p<-lm(uid ~ marks)
print(p)
q<-data.frame(marks=50)
r<-predict(p,q)
print(r)
plot(uid,marks)
plot(uid,marks,col='blue')
plot(uid,marks,col='blue',main = 'uid&marks')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks',type = 'l')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks',type='h')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks',type='s')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks',type='c')
plot(uid,marks,col='blue',main = 'uid&marks',xlab = 'uid',ylab = 'marks',type='n')
age<-c(21,20,25,23)
height<-c(5.5,3.4,6,4.3)
x<-lm(age ~ height)
print(x)
plot(age,height)
