data()
data("women")
print(women)
x=lm(weight~height, data=women)
print(x)
y<-data.frame(height=75)
y1<-predict(x,y)
print(y1)
x=lm(height~weight, data=women)
y<-data.frame(weight=170)
y1<-predict(x,y)
print(y1)
#question1
data(trees)
print(trees)
p=lm(Volume ~ Height, data=trees)
print(p)
q<-data.frame(Height=100)
q1<-predict(p,q)
print(q1)

#question2
print(getwd())
setwd("E:/code/R")
f<-read.csv("Iris.csv")
print(f)
#plot(f)
plot(PetalLengthCm~SepalLengthCm,data=f)

