print(getwd())
setwd("E:/code/R")
print(getwd())
fi<-read.csv("AI lab 29sep.csv")
print(fi)
print(ncol(fi))
print(nrow(fi))
val<-max(fi$HB)
print(val)
val<-subset(fi , HB==max(HB))
print(val)
val<-subset(fi , Gender=="M" & HB>12)
print(val)
val1<-subset(fi , Blood.Pressure=="Normal" & Height>5)
print(val1)
write.csv(val1,"AI lab 29sep.csv")
val2<-read.csv("AI lab 29sep.csv")
print(val2)
f2<-read.table("student.txt", TRUE, sep="," ,quote = "\"")
print(f2)
